### ISSUE TITLE
Discarding packet received on eth0 interface that has no IPv4 address assigned

### ISSUE THREAD

**Issue by iAmSaugata** [modem7/DHCP-Relay#20]
Hi,
I am running DHCP-Relay in container with pihole, and normally it is working fine, but if I reboot the host system, I am getting this error, and no one able to get the IP from DHCP server. Only getting fixed if I reboot the container manually. 

Could you please check or could you please add some delay (30 s) in the image?

```today at 3:28:40 PMRequesting: eth0 as upstream: N downstream: Y
today at 3:28:40 PMRequesting: br_pihole as upstream: Y downstream: N
today at 3:28:40 PMInternet Systems Consortium DHCP Relay Agent 4.4.3
today at 3:28:40 PMCopyright 2004-2022 Internet Systems Consortium.
today at 3:28:40 PMAll rights reserved.
today at 3:28:40 PMFor info, please visit https://www.isc.org/software/dhcp/
today at 3:28:40 PMListening on LPF/br_pihole/02:42:3c:4b:2a:8b
today at 3:28:40 PMSending on   LPF/br_pihole/02:42:3c:4b:2a:8b
today at 3:28:40 PMListening on LPF/eth0/e4:5f:01:68:f8:ac
today at 3:28:40 PMSending on   LPF/eth0/e4:5f:01:68:f8:ac
today at 3:28:40 PMSending on   Socket/fallback
today at 3:28:42 PMDropping request received on br_pihole
today at 3:28:43 PMDropping request received on br_pihole
today at 3:28:53 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:28:55 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:28:57 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:26 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:28 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:33 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:37 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:46 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:47 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:48 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 3:29:52 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.```

**Comment by modem7** [comment]
Have you tried adding a `depends_on`?

**Comment by iAmSaugata** [comment]
I have tried everything.
```#Name : pihole-dhcp-wireguard
version: "2.0"
services:
  # PiHole with Adguard Home DNS
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole.dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8008:80/tcp"
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
        - SYS_NICE
    environment:
      WEBPASSWORD: "MyPass"
      FTLCONF_REPLY_ADDR4: "192.168.0.114"
      ServerIP: "192.168.0.114"
      VIRTUAL_HOST:  "pihole.dns"
      PIHOLE_DNS_: "10.14.59.131#553"
      DNSMASQ_LISTENING: "all"
      PIHOLE_DOMAIN: "local"
      DNSMASQ_USER: "root"
      CUSTOM_CACHE_SIZE: "10000"
      DHCP_ACTIVE: "true"
      DHCP_IPv6: "false"
      IPv6: "false"
      DHCP_START: "192.168.0.10"
      DHCP_END: "192.168.0.249"
      DHCP_ROUTER: "192.168.0.1"
      DHCP_LEASETIME: "24"
      DHCP_rapid_commit: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
    volumes:
      - '/home/pi/pihole-install/pihole/:/etc/pihole/'
      - '/home/pi/pihole-install/dnsmasq.d/:/etc/dnsmasq.d/'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      backend:
        ipv4_address: '172.33.0.100'
      #frontproxy_proxy-tier: {}

  # WireGuard VPN with PiHole DNS
  wg-easy:
    environment:
      # Change this to your host's public address
      WG_HOST: "connect.fqdn"
      # Optional:
      PASSWORD: "MyPass"
      WG_DEFAULT_ADDRESS: "10.8.0.x"
      WG_DEFAULT_DNS: "172.33.0.100"
    image: weejewel/wg-easy:latest
    container_name: wireguard
    hostname: wireguard
    volumes:
      - '/home/pi/wireguard:/etc/wireguard'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE      
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    depends_on:
      - pihole
    networks:
      backend:
      
  # DHCP Helper
  dhcphelper:
    image: modem7/dhcprelay:latest
    container_name: pihole-dhcp-helper
    hostname: dhcp-helper-svr
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    mem_limit: 20m
    mem_reservation: 6m
    network_mode: "host"
    #entrypoint: "sleep 30 && dhcrelay"
    #https://fedoramagazine.org/build-network-bridge-fedora/
    #https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcrelay
    #command: ["30"]
    command: ["-id", "eth0", "-iu", "br_pihole", "172.33.0.100"]
    cap_add:
      - NET_ADMIN
    depends_on:
      pihole:
        condition: service_healthy
networks:
  backend:
    ipam:
      config:
        - subnet: 172.33.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_pihole
  #frontproxy_proxy-tier:
  # external: true```

**Comment by iAmSaugata** [comment]
With the test build, still having same issue after host reboot.

```today at 4:55:49 PMRequesting: eth0 as upstream: N downstream: Y
today at 4:55:49 PMRequesting: br_pihole as upstream: Y downstream: N
today at 4:55:49 PMInternet Systems Consortium DHCP Relay Agent 4.4.3
today at 4:55:49 PMCopyright 2004-2022 Internet Systems Consortium.
today at 4:55:49 PMAll rights reserved.
today at 4:55:49 PMFor info, please visit https://www.isc.org/software/dhcp/
today at 4:55:49 PMListening on LPF/br_pihole/02:42:a5:20:36:ec
today at 4:55:49 PMSending on   LPF/br_pihole/02:42:a5:20:36:ec
today at 4:55:49 PMListening on LPF/eth0/e4:5f:01:68:f8:ac
today at 4:55:49 PMSending on   LPF/eth0/e4:5f:01:68:f8:ac
today at 4:55:49 PMSending on   Socket/fallback
today at 4:55:49 PMDropping request received on br_pihole
today at 4:55:50 PMDropping request received on br_pihole
today at 4:55:53 PMDropping request received on br_pihole
today at 4:55:53 PMDropping request received on br_pihole
today at 4:56:46 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:56:48 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:56:52 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:00 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:16 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:26 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:28 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:32 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:40 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:57:57 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:03 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:05 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:09 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:17 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:33 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:40 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:42 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:45 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:58:53 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:59:09 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:59:16 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:59:18 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:59:22 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:59:30 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.
today at 4:59:45 PMDiscarding packet received on eth0 interface that has no IPv4 address assigned.

**Comment by modem7** [comment]
With the latest `test` image, does the healthcheck kick in?

We can override the healthcheck timings to see if this restarts the container:

```
    healthcheck:
      test: nc -uzvw3 127.0.0.1 67 || exit 1
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 3
```

**Comment by iAmSaugata** [comment]
Yes, it is healthy in status.

**Comment by modem7** [comment]
Try disabling `DHCP_rapid_commit:` - as it's only two messages, it may be causing some issues.

This is my current setup (without the relay as my router now deals with it):

```
 #Pihole - Network wide adblocker, DNS cache and DHCP server
  pihole:
    image: pihole/pihole:latest
    container_name: Pihole
    hostname: PiHole-Master
    environment:
      # INTERFACE: $INTERFACE
      DNSMASQ_LISTENING: $DNSMASQ_LISTENING
      # ServerIP: $SERVER_IP
      # DNS1: $PH_DNS1
      # DNS2: $PH_DNS2
      PIHOLE_DNS_: $PIHOLE_DNS
      # VIRTUAL_HOST: $VIRTUAL_HOST
      FTLCONF_REPLY_ADDR4: $SERVER_IP
      CORS_HOSTS: $CORS_HOSTS
      TZ: $TZ
      SKIPGRAVITYONBOOT: $SKIPGRAVITYONBOOT
      DNSSEC: $DNSSEC
      DNS_BOGUS_PRIV: $DNS_BOGUS_PRIV
      DNS_FQDN_REQUIRED: $DNS_FQDN_REQUIRED
      REV_SERVER: $REV_SERVER
      DNSMASQ_USER: $DNSMASQ_USER
      REV_SERVER_TARGET: $REV_SERVER_TARGET
      REV_SERVER_CIDR: $REV_SERVER_CIDR
      REV_SERVER_DOMAIN: $REV_SERVER_DOMAIN
      CUSTOM_CACHE_SIZE: $CUSTOM_CACHE_SIZE
      WEBPASSWORD: $WEBPASSWORD
      WEBTHEME: default-dark
      FTLCONF_RATE_LIMIT: 0/0
      FTLCONF_MOZILLA_CANARY: $MOZILLA_CANARY
      FTLCONF_BLOCK_ICLOUD_PR: $BLOCK_ICLOUD_PR
    labels: 
      - "autoheal=true"
    cap_add:
      - NET_ADMIN
      - CAP_CHOWN
      - CAP_SYS_NICE
      - CAP_NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    network_mode: "host"
    dns:
      - "127.0.0.1"
      - "9.9.9.9"
    depends_on:
      - dnscrypt-proxy
    volumes:
      - $USERDIR/Pihole/etc/pihole:/etc/pihole/
      - $USERDIR/Pihole/etc/dnsmasq:/etc/dnsmasq.d/
      # run `touch $USERDIR/Pihole/etc/logs/pihole.log` first unless you like errors
      - $USERDIR/Pihole/etc/logs/pihole.log:/var/log/pihole.log
      - $PIBACKUPDIR:/backup
      - $PISCRIPTS/piholebackup.sh:/scripts/piholebackup.sh:ro
    restart: always
    mem_limit: 2048m
    mem_reservation: 256m
```

**Comment by iAmSaugata** [comment]
Health check didn't work, I will check by disabling DHCP_rapid_commit

**Comment by modem7** [comment]
Unfortunately this is quite a simple container that just installs the dhchelper, there's not really much else it does bar act as a relay. 

From what I remember when I was still using it in production, `Discarding packet received on eth0 interface that has no IPv4 address assigned.` was a common message, but did not affect the devices on my LAN.

**Comment by iAmSaugata** [comment]
No luck with disabling DHCP_rapid_commit.

**Comment by modem7** [comment]
Wait, just having a further look at your compose file.

You don't seem to have `- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server`

Might help?

**Comment by modem7** [comment]
Just found my old compose file:

```
 #############
 ##DHCPRelay##
 #############
 
 #DHCPRelay - DHCP Relay between host network and PiHole bridge
  dhcprelay:
    image: modem7/dhcprelay:latest
    container_name: DHCPRelay
    command: ["-id", "eno1", "-iu", "br_pihole", "172.33.0.100"] #https://fedoramagazine.org/build-network-bridge-fedora/
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: always
    mem_limit: 20m
    mem_reservation: 5m

 ##########
 ##Pihole##
 ##########
 
 #Pihole - Network wide adblocker, DNS cache and DHCP server
  pihole:
    image: pihole/pihole:latest
    container_name: PiHole
    hostname: PiHole
    environment:
      INTERFACE: $INTERFACE
      DNSMASQ_LISTENING: $DNSMASQ_LISTENING
      ServerIP: $ServerIP
      DNS1: $PH_DNS1
      DNS2: $PH_DNS2
      VIRTUAL_HOST: $VIRTUAL_HOST
      TZ: $TZ
      SKIPGRAVITYONBOOT: "true"
    labels: 
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pihole-rtr.entrypoints=https"
      - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.$DOMAINNAME`)"
      - "traefik.http.routers.pihole-rtr.priority=99"
      - "traefik.http.routers.pihole-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.pihole-rtr.middlewares=chain-authelia@file, pihole-add-admin" # Authelia
      - "traefik.http.middlewares.pihole-add-admin.addPrefix.prefix=/admin"
      ## HTTP Services
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
     # Healthcheck
      - "traefik.http.services.pihole-svc.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.pihole-svc.loadbalancer.healthcheck.timeout=5s"
    cap_add:
      - NET_ADMIN
    networks:
      pihole:
        ipv4_address: '172.22.0.100'
      docker-macvlan:
        ipv4_address: '192.168.0.2'
    dns:
      - 127.0.0.1
      - 9.9.9.9
    ports:
      - "53:53"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    depends_on:
      - dhcprelay
      - dnscrypt-proxy
    volumes:
      - Pihole:/etc/pihole/
      - Dnsmasq:/etc/dnsmasq.d/
      # - $USERDIR/Pihole/pihole:/etc/pihole/
      # - $USERDIR/Pihole/dnsmasq.d:/etc/dnsmasq.d/
    restart: always
    mem_limit: 500m
    mem_reservation: 250m

 ##~~~~~~~~~~~~~~~~~~~~~##
 ##Network Configuration##
 ##~~~~~~~~~~~~~~~~~~~~~##

networks:
  pihole:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.22.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_pihole #https://stackoverflow.com/questions/43981224/docker-how-to-set-iface-name-when-creating-a-new-network

  internal:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.33.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_internal #https://stackoverflow.com/questions/43981224/docker-how-to-set-iface-name-when-creating-a-new-network

  docker-macvlan:
    driver: macvlan
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
    driver_opts:
      parent: eno2
```
