### ISSUE TITLE
Configuration for DHCPv6

### ISSUE THREAD

**Issue by Ririshi** [modem7/DHCP-Relay#38]
I've been struggling to set this up for an DHCPv6 so I can use my PiHole to set up an ULA network locally. The DHCPv4 version works fine, but for some reason DHCPv6 is not getting relayed correctly.

My host is a Raspberry Pi 4B running RaspberryOS 11. The interface I'm using is `eth0` with link-local address `fe80::a7fa:cad4:1ca:4de`. It has a GUA address as well but it isn't static. I want to use the PiHole Docker container to advertise a prefix so it can get an ULA address, which can then be used to relay other DHCPv6 traffic to the Docker container.

Maybe I'm trying something that's simply not possible, but I'm hoping I can get this set up.

For the DHCPv6 setup, I'm using this setup in my PiHole's `/etc/dnsmasq.d/08-enable-ra-ula.conf`:

```
enable-ra
dhcp-option=option6:dns-server,[fd00::]
dhcp-range=fd00:dead:beef:fade::1:0,fd00:dead:beef:fade::1:ffff,64,24h
ra-param=eth0,5,0
```

My `docker-compose.yml` looks like this:

```yml
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    environment:
      TZ: 'Europe/Amsterdam'
      FTLCONF_LOCAL_IPV4: '192.168.0.10'
      FTLCONF_LOCAL_IPV6: 'fe80::a7fa:cad4:1ca:4de'
      DNS_FQDN_REQUIRED: 'true'
      DNS_BOGUS_PRIV: 'true'
      PIHOLE_DNS_: '208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53'
      WEBTHEME: 'default-auto'
      REV_SERVER: 'true'
      REV_SERVER_TARGET: '192.168.0.1'
      REV_SERVER_CIDR: '192.168.0.0/24'
      DHCP_ACTIVE: 'true'
      DHCP_START: '192.168.0.20'
      DHCP_END: '192.168.0.200'
      DHCP_ROUTER: '192.168.0.1'
      DHCP_rapid_commit: 'true'
      VIRTUAL_HOST: 'pi.hole'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    depends_on:
      - dhcp-v4-relay
      - dhcp-v6-relay
    networks:
      reverse_proxy: {}
      backend:
        ipv4_address: '172.31.0.100'
        ipv6_address: 'fd00:dead:beef:fade::100'
    restart: unless-stopped

  dhcp-v4-relay:
    image: modem7/dhcprelay:latest
    container_name: dhcp-v4-relay
    command: ["-4", "-i", "eth0", "-i", "br-pihole", "172.31.0.100"]
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

  dhcp-v6-relay:
    image: modem7/dhcprelay:latest
    container_name: dhcp-v6-relay
    command: ["-6", "-l", "eth0", "-u", "fd00:dead:beef:fade::100%br-pihole"]
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

networks:
  reverse_proxy:
    name: nginx-reverse-proxy
    external: true
  backend:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-pihole
    ipam:
      config:
        - subnet: 172.31.0.0/16
        - subnet: fd00:dead:beef:fade::/64
```
